---
- name: Install Nginx
  hosts: all  # Replace with your server's hostname or group name
  become: true  # Run tasks with sudo/root privileges

  tasks:

    - name: install leatest version of nginx
      yum:
        name: nginx
        state: absent

    